import os

import pandas as pd

from gws_core import (
    ConfigParams,
    ConfigSpecs,
    File,
    InputSpec,
    InputSpecs,
    OutputSpec,
    OutputSpecs,
    StrParam,
    Table,
    TableImporter,
    Task,
    TaskFileDownloader,
    TaskInputs,
    TaskOutputs,
    task_decorator,
)


@task_decorator("Ec_number", human_name="Ec number",
                short_description="Mapping blast result to EC number database.")
class ECnumber(Task):
    """
    EC number determination.

    This task allows getting EC numbers for digital twins reconstruction. It uniprot/swissprot database to map EC number. It takes table generated by Diamond task.
    For instance, this task maps Diamond results to EC numbers using the FUNGI EC number database.
    """

    _BASE_URL = 'https://storage.gra.cloud.ovh.net/v1/AUTH_a0286631d7b24afba3f3cdebed2992aa/opendata/omix/db'

    # Maps organism group → database filename (extend this dict when new groups are added)
    _DB_FILES: dict = {
        'fungi': 'fungi_EC_number_database_uniprot.tsv',
    }

    input_specs: InputSpecs = InputSpecs({
        'input_table': InputSpec((Table, File), human_name="diamond result", short_description="Diamond result as Table or TSV/CSV File")
    })

    output_specs: OutputSpecs = OutputSpecs({
        'output_table': OutputSpec(Table, human_name="EC number result", short_description="Table containing EC numbers mapped from Diamond results"),
        'output_file': OutputSpec(File, human_name="EC number file", short_description="Text file with one EC number per line")
    })

    config_specs = ConfigSpecs({
        'taxonomy': StrParam(
            default_value='fungi',
            allowed_values=['fungi'],
            human_name='Organism group',
            short_description='Taxonomic group used to select the EC number reference database.',
        )
    })

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:

        input_resource = inputs['input_table']
        if isinstance(input_resource, Table):
            input_table = input_resource
        elif isinstance(input_resource, File):
            ext = os.path.splitext(input_resource.path)[1].lower()
            delimiter = "," if ext == ".csv" else "\t"
            input_table = TableImporter.call(
                input_resource,
                {"delimiter": delimiter, "header": 0, "index_column": 0, "comment": "#"}
            )
        else:
            raise RuntimeError("Unsupported type for 'input_table' (expected Table or File).")

        taxonomy = params['taxonomy']
        ec_blast_table = self.call_ecnumber(input_table, taxonomy)

        # Write EC numbers to a text file (one per line)
        ec_file_path = os.path.join(self.create_tmp_dir(), 'ec_numbers.txt')
        ec_numbers = list(ec_blast_table.get_data()["EC number"]) if ec_blast_table.get_data().shape[0] > 0 else []
        with open(ec_file_path, 'w') as f:
            f.write('EC number\n')
            f.write('\n'.join(ec_numbers) + ('\n' if ec_numbers else ''))

        return {
            'output_table': ec_blast_table,
            'output_file': File(ec_file_path)
        }

    def call_ecnumber(self, input_table: Table, taxonomy: str) -> Table:
        db_filename = self._DB_FILES[taxonomy]
        db_url = f'{self._BASE_URL}/{db_filename}'

        file_downloader = TaskFileDownloader(
            brick_name=ECnumber.get_brick_name(),
            message_dispatcher=self.message_dispatcher
        )

        ec_database_file = file_downloader.download_file_if_missing(
            db_url, filename=db_filename, decompress_file=False
        )

        intable = input_table.get_column_data("Subject ID")
        processed_data = []
        for value in intable:
            # Extract information from each value in the "Subject ID" column and keep only the integer section
            data = value.split('.')[0]
            processed_data.append(data)

        # read the databse file
        mapping_dict: dict[str, list[str]] = {}
        with open(ec_database_file) as mapping_file:
            header = mapping_file.readline().strip().split('\t')
            entry_index = header.index('Entry')
            ec_number_index = header.index('EC number')

            for line in mapping_file:
                columns = line.strip().split('\t')
                entry = columns[entry_index]
                ec_numbers = columns[ec_number_index].split(';')
                mapping_dict[entry] = ec_numbers

        # compare database file to diamond table
        processed_ec_numbers = set()
        # Create a list to store the processed EC numbers

        for entry in processed_data:
            if entry in mapping_dict and mapping_dict[entry]:
                for ec_number in mapping_dict[entry]:
                    ec_number_stripped = ec_number.strip()
                    if ec_number_stripped and ec_number_stripped not in processed_ec_numbers:
                        processed_ec_numbers.add(ec_number_stripped)

        # Create a Table with the processed EC numbers (empty-safe)
        df = pd.DataFrame({"EC number": sorted(processed_ec_numbers)})
        result = Table(df)
        return result
