# LICENSE
# This software is the exclusive property of Gencovery SAS.
# The use and distribution of this software is prohibited without the prior consent of Gencovery SAS.
# About us: https://gencovery.com

from pathlib import Path
from typing import Final, List, Optional

from gws_core import (
    ConfigParams, ConfigSpecs, File,
    InputSpec, InputSpecs, IntParam, OutputSpec, OutputSpecs,
    ResourceSet, ShellProxy, StrParam, Task, TaskInputs, TaskOutputs,
    BoolParam,
    task_decorator
)

# If you have a dedicated env helper for MSA/IQ-TREE, you can reuse it here
from .phytreeviz_env import PhytreevizShellProxyHelper


@task_decorator(
    "PhyTreeViz",
    human_name="Phylogenetic Tree Visualization (phyTreeViz)",
    short_description="Render a phylogenetic tree figure from a Newick file using phyTreeViz"
)
class PhyTreeViz(Task):
    """
    Visualizes a phylogenetic tree using the phyTreeViz package and produces
    a high-quality figure (PNG).

    **Input**

    - `tree_file` (File)
      Phylogenetic tree file, typically in **Newick** format.
      In a typical workflow, this is the `<prefix>.treefile` output from the
      IQ-TREE Task (maximum-likelihood tree with branch lengths and optionally
      bootstrap/confidence values).

    **Outputs**

    - `tree_figure` (File)
      PNG figure generated by phyTreeViz: `<prefix>.tree.png`.

    - `phytreeviz_log` (File)
      Wrapper log file: `<prefix>.phytreeviz_wrapper.log`.

    **Main parameter**

    - `prefix` (string, default: tree filename stem)
      Base name for outputs. Final figure will be `<prefix>.tree.png`.

    **Advanced figure appearance parameters**

    - `fig_height`
      Effective height per leaf node = `fig_height * 0.1`.
      With default `fig_height = 3`, you get ~0.3 per leaf, suitable for
      medium/large trees.

    - `fig_width`
      Effective figure width = `fig_width * 0.1`.
      With default `fig_width = 120`, you get 12.0 units width.

    - `leaf_label_size`
      Font size for tip labels (default 8).

    - `ignore_branch_length`
      If true, plot the tree ignoring branch lengths (more compact horizontally).

    - `align_leaf_label`
      Align leaf labels vertically for a clean column on the right.

    - `show_branch_length`
      Show numeric branch lengths on edges (tends to be cluttered for large trees).

    - `show_confidence`
      Show confidence / bootstrap values on branches **if they are present in
      the Newick** (e.g. IQ-TREE `-bb` or `-b` runs).

    - `dpi`
      Figure resolution (dots per inch). 300 is standard for print.
    """

    # ---------- I/O specs ----------

    input_specs: Final[InputSpecs] = InputSpecs({
        "tree_file": InputSpec(
            File,
            human_name="Phylogenetic tree (Newick)",
            short_description="Tree file, typically <prefix>.treefile produced by IQ-TREE."
        )
    })

    output_specs: Final[OutputSpecs] = OutputSpecs({
        "tree_figure": OutputSpec(
            File,
            human_name="Phylogenetic tree figure (PNG)"
        ),
        "phytreeviz_log": OutputSpec(
            File,
            human_name="phyTreeViz wrapper log"
        ),
    })

    # ---------- configuration (with advanced appearance options) ----------

    config_specs: Final[ConfigSpecs] = ConfigSpecs({
        "prefix": StrParam(
            default_value="",
            short_description="Output prefix (default: tree filename stem)."
        ),
        # Advanced figure options (scaled by 0.1 in run())
        "fig_height": IntParam(
            default_value=3,   # -> 0.3 per leaf
            min_value=1,
            short_description=(
                "[Advanced] Figure height per leaf node multiplied by 0.1. "
                "Effective default ~0.3 (0.1 * 3). Increase for more vertical spacing."
            )
        ),
        "fig_width": IntParam(
            default_value=120,  # -> 12.0
            min_value=10,
            short_description=(
                "[Advanced] Figure width multiplied by 0.1. "
                "Effective default ~12.0 (0.1 * 120). Increase for very large trees."
            )
        ),
        "leaf_label_size": IntParam(
            default_value=8,
            min_value=1,
            short_description="[Advanced] Leaf label font size (Default: 8)."
        ),
        "ignore_branch_length": BoolParam(
            default_value=True,
            short_description=(
                "[Advanced] Ignore branch length for plotting tree "
                "(Default: ON = more compact tree)."
            )
        ),
        "align_leaf_label": BoolParam(
            default_value=True,
            short_description=(
                "[Advanced] Align leaf label positions vertically for cleaner layout "
                "(Default: ON)."
            )
        ),
        "show_branch_length": BoolParam(
            default_value=False,
            short_description=(
                "[Advanced] Show branch length values on edges (Default: OFF)."
            )
        ),
        "show_confidence": BoolParam(
            default_value=True,
            short_description=(
                "[Advanced] Show confidence / bootstrap values on branches "
                "(Default: ON, if present in the tree)."
            )
        ),
        "dpi": IntParam(
            default_value=300,
            min_value=50,
            short_description="[Advanced] Figure DPI / resolution (Default: 300)."
        ),
    })

    # ---------- helpers ----------

    def _read_log_tail(self, log_path: Path, max_lines: int = 80) -> str:
        if not log_path.is_file():
            return ""
        try:
            return "\n".join(log_path.read_text(errors="ignore").splitlines()[-max_lines:])
        except Exception:
            return ""

    def _list_dir_files(self, directory: Path) -> str:
        if not directory.is_dir():
            return "<directory does not exist>"
        names: List[str] = sorted(p.name for p in directory.iterdir())
        if not names:
            return "<no files>"
        return "\n".join(names)

    # ---------- main run ----------

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        tree_file: File = inputs["tree_file"]

        # Use the same environment helper as MSA/IQ-TREE so everything lives in one env
        shell: ShellProxy = PhytreevizShellProxyHelper.create_proxy(self.message_dispatcher)

        work_dir = Path(shell.working_dir)
        out_dir = work_dir / "phytreeviz"
        out_dir.mkdir(parents=True, exist_ok=True)

        prefix = (params["prefix"] or Path(tree_file.path).stem).strip() or "tree"

        worker = Path(__file__).with_name("_phyTreeViz.py")

        # Convert scaled IntParam fig_height/fig_width back to float values
        fig_height = params["fig_height"] * 0.1   # 3 -> 0.3
        fig_width = params["fig_width"] * 0.1     # 120 -> 12.0

        cmd_parts = [
            "python3",
            str(worker),
            "--tree",    f"\"{tree_file.path}\"",
            "--out",     f"\"{out_dir}\"",
            "--prefix",  f"\"{prefix}\"",
            "--fig-height", str(fig_height),
            "--fig-width",  str(fig_width),
            "--leaf-label-size", str(params["leaf_label_size"]),
            "--dpi", str(params["dpi"]),
        ]

        if params["ignore_branch_length"]:
            cmd_parts.append("--ignore-branch-length")
        if params["align_leaf_label"]:
            cmd_parts.append("--align-leaf-label")
        if params["show_branch_length"]:
            cmd_parts.append("--show-branch-length")
        if params["show_confidence"]:
            cmd_parts.append("--show-confidence")

        cmd_str = " ".join(cmd_parts)
        print("[DEBUG] phyTreeViz worker cmd:", cmd_str)

        rc = shell.run(cmd_str, shell_mode=True)

        fig_path = out_dir / f"{prefix}.tree.png"
        log_path = out_dir / f"{prefix}.phytreeviz_wrapper.log"

        if rc:
            tail = self._read_log_tail(log_path)
            raise RuntimeError(f"phyTreeViz worker failed. See log tail:\n{tail}")

        if not fig_path.is_file():
            files = self._list_dir_files(out_dir)
            tail = self._read_log_tail(log_path)
            raise RuntimeError(
                f"Tree figure not found: {fig_path}\n\n"
                f"Files present in {out_dir}:\n{files}\n\n"
                f"Log tail:\n{tail}"
            )

        tree_figure = File(str(fig_path))
        phytreeviz_log = File(str(log_path)) if log_path.is_file() else None

        return {
            "tree_figure": tree_figure,
            "phytreeviz_log": phytreeviz_log,
        }
