#!/usr/bin/env python3
# LICENSE
# Exclusive property of Gencovery SAS
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Gencovery SAS, 2024

from pathlib import Path
from typing import Final, List, Optional

from gws_core import (
    ConfigParams, ConfigSpecs, File, Folder,
    InputSpec, InputSpecs, OutputSpec, OutputSpecs,
    ResourceSet, ShellProxy, StrParam, Task, TaskInputs, TaskOutputs,
    task_decorator
)

from .pygenomeviz_env import PyGenomeVizShellProxyHelper


@task_decorator(
    "PyGenomeViz",
    human_name="Genome Visualization (pyGenomeViz)",
    short_description="Interactive visualization of multiple GenBank genomes"
)
class PyGenomeViz(Task):
    """
    Visualizes multiple GenBank genomes using pyGenomeViz core API.

    **Input**
    - `genbank_folder` (Folder): Folder containing one or more GenBank files (.gb, .gbk, .genbank)

    **Output**
    - `interactive_html` (Folder): Folder containing the interactive HTML visualization
    - `pygenomeviz_outputs` (ResourceSet): Any additional files generated by pyGenomeViz worker
    """

    # ---------- I/O specs ----------
    input_specs: Final[InputSpecs] = InputSpecs({
        "genbank_folder": InputSpec(
            Folder,
            human_name="GenBank folder",
            short_description="Folder containing one or more GenBank files"
        )
    })

    output_specs: Final[OutputSpecs] = OutputSpecs({
        "interactive_html": OutputSpec(
            Folder,
            human_name="Interactive HTML output"
        ),
        "pygenomeviz_outputs": OutputSpec(
            ResourceSet,
            human_name="Additional pyGenomeViz output files"
        )
    })

    # ---------- configuration ----------
    config_specs: Final[ConfigSpecs] = ConfigSpecs({
        "prefix": StrParam(
            default_value="pygenomeviz",
            short_description="Output HTML file prefix"
        )
    })

    # ---------- helpers ----------
    def _read_log_tail(self, log_path: Path, max_lines: int = 80) -> str:
        if not log_path.is_file():
            return ""
        try:
            return "\n".join(log_path.read_text(errors="ignore").splitlines()[-max_lines:])
        except Exception:
            return ""

    def _list_dir_files(self, directory: Path) -> str:
        if not directory.is_dir():
            return "<directory does not exist>"
        names: List[str] = sorted(p.name for p in directory.iterdir())
        if not names:
            return "<no files>"
        return "\n".join(names)

    # ---------- main run ----------
    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        genbank_folder: Folder = inputs["genbank_folder"]

        # Create shell proxy
        shell: ShellProxy = PyGenomeVizShellProxyHelper.create_proxy(self.message_dispatcher)

        work_dir = Path(shell.working_dir)
        out_dir = work_dir / "pygenomeviz"
        out_dir.mkdir(parents=True, exist_ok=True)

        prefix = (params["prefix"] or "pygenomeviz").strip() or "pygenomeviz"
        worker = Path(__file__).with_name("_pyGenomeViz.py")

        cmd_parts = [
            "python3",
            str(worker),
            "--in", f"\"{genbank_folder.path}\"",
            "--out", f"\"{out_dir}\"",
            "--prefix", f"\"{prefix}\"",
        ]
        cmd_str = " ".join(cmd_parts)
        print("[DEBUG] pyGenomeViz worker cmd:", cmd_str)

        # Run worker
        rc = shell.run(cmd_str, shell_mode=True)
        resource_set = ResourceSet()

        # Define log path
        wrapper_log_path = out_dir / f"{prefix}.pygenomeviz_wrapper.log"

        # Collect auxiliary outputs (everything except main HTML and wrapper log)
        for p in sorted(out_dir.iterdir()):
            if not p.is_file():
                continue
            if p.suffix.lower() == ".html" or p == wrapper_log_path:
                continue
            resource_set.add_resource(File(str(p)), p.name)

        # Error handling
        if rc != 0:
            tail = self._read_log_tail(wrapper_log_path)
            files_list = self._list_dir_files(out_dir)
            raise RuntimeError(
                f"pyGenomeViz worker failed with exit code {rc}.\n"
                f"Files present in {out_dir}:\n{files_list}\n"
                f"Log tail:\n{tail}"
            )

        # Ensure at least one HTML file exists
        html_files = list(out_dir.glob("*.html"))
        if not html_files:
            tail = self._read_log_tail(wrapper_log_path)
            files_list = self._list_dir_files(out_dir)
            raise RuntimeError(
                "pyGenomeViz completed without generating any HTML file.\n"
                f"Files present in {out_dir}:\n{files_list}\n"
                f"Log tail:\n{tail}"
            )

        return {
            "interactive_html": Folder(str(out_dir)),
            "pygenomeviz_outputs": resource_set
        }
